name: Update Sheet ${{ github.ref }} ENV

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  update_sheets:
    name: Updating Sheets for ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment : input.environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main Python script
        run: python main.py
