name: Update Sheet

on:
  push:
    branches:
      - main
  # schedule:
    # - cron: '*/15 * * * *'

jobs:
  update_sheets:
    name: Updating Sheets for ${{ github.ref_name }} Environment
    runs-on: ubuntu-latest
    environment: dev
    env:
      CHECKER_VARIABLE: ${{vars.CHECKER_VARIABLE}}
      SERVICE_ACCOUNT_TYPE: ${{secrets.SERVICE_ACCOUNT_TYPE}}
      PROJECT_ID: ${{secrets.PROJECT_ID}}
      PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      AUTH_URI: ${{secrets.AUTH_URI}}
      TOKEN_URI: ${{secrets.TOKEN_URI}}
      AUTH_PROVIDER_CERT_URL: ${{secrets.AUTH_PROVIDER_CERT_URL}}
      CLIENT_CERT_URL: ${{secrets.CLIENT_CERT_URL}}
      UNIVERSE_DOMAIN: ${{secrets.UNIVERSE_DOMAIN}}
      SHEETS_ID: ${{secrets.SHEETS_ID}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main Python script
        run: python main.py
    

