name: Update Sheet

on:
  push:
    branches:
      - dev
      - main
  # schedule:
  #   - cron: '*/30 * * * *'

jobs:
  update-sheets:
    uses: ./.github/workflows/reusable_update_sheets.yml
    with:
      branch_name: ${{ github.ref_name }}
