name: Update Sheet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update_sheets:
    name: Updating Sheets for Production Environment
    runs-on: ubuntu-latest
    environment: ${{vars.ENV}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create JSON Credentials
        run: echo "${{ secrets.JSON_CREDENTIALS}}" > credentials.json
      
      - name: Create DOTENV
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Show Dir files
        run: |
          ls -a

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main Python script
        run: python main.py
    

